# fly.toml app configuration file generated for vigilant-octopus on 2023-09-29T20:51:49+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vigilant-octopus"
primary_region = "mad"

[build]
builder = "heroku/buildpacks:20"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
